### ISSUE TITLE
Support for Ubuntu security API

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/konf#3]
We need to add new Ingress rule for ubuntu.com for a service that will be using an external Docker image. Currently this is not supported.

I think the best approach will be to add new property for routes, like `independent: true`. 

In the konf file for ubuntu.com it will be something like:
```yaml
  routes:
    - paths: [/security-api]
      name: security-api
      independent: true
```

**Konf modifications:**

1. We add a condition to skip the Service and Deployment objects for routes with `independent: true`. That should be done here between line 4 and 5 with `{% if not independent %}`:
https://github.com/canonical-web-and-design/konf/blob/849f537cf69dfa5219e5611e97c72ab3c97fe6a8/templates/site.yaml#L4-L8
And 
https://github.com/canonical-web-and-design/konf/blob/849f537cf69dfa5219e5611e97c72ab3c97fe6a8/templates/site.yaml#L14-L18

2. We add a `--no-ingress` argument for `konf.py` that will be used for another `if` statement here:
https://github.com/canonical-web-and-design/konf/blob/849f537cf69dfa5219e5611e97c72ab3c97fe6a8/templates/site.yaml#L21

I think this way is a good aproach to continue using the konf snap for both services.

**Comment by nottrobin** [comment]
Rather than `--no-ingress` option, couldn't we just not include the domain name and other ingress related properties in the yaml file and infer from that that there's no ingress?

I don't see why you need "independent" - isn't that section just a mapping of routes to service names? The services themselves are defindd elsewhere aren't they?

**Comment by jkfran** [comment]
> Rather than `--no-ingress` option, couldn't we just not include the domain name and other ingress related properties in the yaml file and infer from that that there's no ingress?

Unfortunately, the domain is an essential property right now, we generate the Deployment and Services names from it. Also, all the other related properties with the ingress are optional. In this case, I think it's better to choose not to generate the ingress output by a CLI argument.

> I don't see why you need "independent" - isn't that section just a mapping of routes to service names? The services themselves are defindd elsewhere aren't they?

No, check the konf file of ubuntu.com as a reference:
https://github.com/canonical-web-and-design/ubuntu.com/blob/806a0c3813f9e16f6ffc051c3b54f1cdc2830d37/konf/site.yaml#L69-L87

We generate the Services and Deployment from here and this allows us to nest konf properties again in the routes definition, like 
`image`, `replicas`, `memoryLimit`, etc...

But now that you mention this instead of `independent` we could reuse another property like `image` so if `image` is not declared konf assume that we are only interested in the ingress file.

WDYT?

**Comment by nottrobin** [comment]
> Unfortunately, the domain is an essential property right now, we generate the Deployment and Services names from it. Also, all the other related properties with the ingress are optional. In this case, I think it's better to choose not to generate the ingress output by a CLI argument.

Right, so this would imply that what we really want here is a more fundamental restructure of how those properties work, so services can be defined independently of a domain name.

To my mind, the main reason for `konf` to exist (over simply writing k8s configs) is to codify our best practices. And so, if we're now saying that it's okay for services to be standalone, we should properly consider what that means, and change our tooling to encourage the most semantic and simple structure for that new reality.

This is why I don't think it's a good idea to try to quickly change Konf to support the new security API right now, as it's gonna be rushed and Konf will end up in a mess.

> we could reuse another property like image

It wouldn't be `image`. Kubernetes hosts our websites using the following pieces:

- The app image is deployed into a number of replicated `pod`s (usually 5)
- The pods are collected together in a `replicaset`
- The `replicaset` is managed through a `deployment` (for rollout status, rollbacks)
- The `deployment` is then expose to the rest of Kubernetes through a `service`, usually by creating an HTTP interface on port 80
- An `ingress` then tells Kubernetes to route requests to that `service`, through its defined `routes`

So, in Kubernetes language, what we're doing here is saying:

- There is an `ingress` that handles all traffic looking for `ubuntu.com`. It will route traffic as follows:
   - Most traffic under `/` will be sent to the `ubuntu-com` service (and handled by its collection of 5 pods)
   - `/tutorials` will be sent to the `ubuntu-com-tutorials` service (and handled by its separate collection of 5 pods)
   - `/blog` will be sent to the `ubuntu-com-blog` service
   - And now, `/security/notices.json` will be sent to `ubuntu-security-api` or something

Therefore, the sensible place to split the relationship between the `ubuntu.com` repo and the `ubuntu.com security api` repo (or whatever it's called) is that `ubuntu.com` tells k8s which service to route traffic to, and `ubuntu.com security api` defines that service. The `ubuntu.com` konf file therefore shouldn't know or care about images for that service.

> We generate the Services and Deployment from here and this allows us to nest konf properties again in the routes definition, like image, replicas, memoryLimit, etc...

Yes, I see. Following on from what I said above about wanting to use the structure of Konf to enforce good patterns, I think we want to consider this quite carefully. The structure you have here at the moment is very much tailored to ubuntu.com, in that it assumes that what you want to use routes for is to route to other `services` that are *built from that same codebase*. This absolutely made sense up to now, because `ubuntu.com` was the only place we were doing this.

However, this structure is somewhat unnatural to Kubernetes, because it blurs the very clear separation between ingresses and services that exist in Kubernetes. And we see that now that we want to split things up along that boundary.

So the question is, do we still consider the assumption that one codebase is going to be controlling the services behind all the routes to be a useful assumption? I think maybe not. I think we'll probably want to do this pattern of splitting out services into other projects more and more (I was just exploring another scenario like this with @jpmartinspt).

So I think we may well want to break this coupling of services to routes going forward.

**Comment by jkfran** [comment]
> This is why I don't think it's a good idea to try to quickly change Konf to support the new security API right now, as it's gonna be rushed and Konf will end up in a mess.

I think this is going to be a blocker. Right now we can't just use raw k8s configs for the new service and continue using `konf` for ubuntu.com.

I don't think it has to end up in a mess, we have been doing changes like this one along the way to support cronjobs and to support the demo service, we can discuss what would be the best solution but this is the best moment to do it in my opinion.

> The ubuntu.com konf file therefore shouldn't know or care about images for that service.

Not in the K8s world but here it does, it's needed to generate the Service. That's why I proposed this one.

> However, this structure is somewhat unnatural to Kubernetes, because it blurs the very clear separation between ingresses and services that exist in Kubernetes. And we see that now that we want to split things up along that boundary.

Yes, we agreed on this in the past just to adapt Konf to the ubuntu.com project.

> I think we'll probably want to do this pattern of splitting out services into other projects more and more

I don't have any objections, this will require changes in the ubuntu.com project. I don't want this to be a blocker for @albertkol, maybe I got the wrong impression in the meeting that we had, I thought it was important to unblock it and `konf` has been receiving changes to serve us when we needed it, let's discuss how these changes should be and unblock.
