### ISSUE TITLE
Domain sharing same TLS cert should use same K8s secret

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/konf#7]
Origin: https://chat.canonical.com/canonical/pl/qkepzrxcw3rk98dj3q19dw1j4r

```
font.ubuntu.com
www.font.ubuntu.com
```

Those 2 domains share the same TLS certificate but use different secrets. This involved an issue because when expired, one secret was updated but not the other.

We should find a way to share the same k8s secret between domains that share the same TLS cert. This will help renewing certificates in only one place.

**Comment by jkfran** [comment]
This issue has been fixed already, the main issue was that we don't support `www` for subdomains (font.ubuntu.com -> www.font.ubuntu.com) on Konf. This was a decision done at the beginning so this domain was an exception and was causing issues with the TLS certificate from time to time.

This issue is now gone since we requested the decommission of www.font.ubuntu.com to IS (rt #129690).
